#!/usr/bin/env python3
"""Generate data/title_screen_overlay.png (2532x1532 RGBA, mostly transparent).

The overlay is alpha-composited by StaticModBuilder's TitleScreenPatcher onto the
vanilla title screen artwork (MENU_Title_EldenRing_01): the SpeedFog Racing
wordmark centered above the ELDEN RING logo, per speedfog-racing's graphic
charter (docs/GRAPHIC_CHARTER.md there): SPEEDFOG in Barlow Condensed 700
off-white #e8e6e1, RACING in Barlow Condensed 600 brass #c8a44e, 0.04em
tracking, and the brass hero route underline beneath (start triangle, line,
station ring, line, terminal square). The badge no longer sits on the TM
glyph's spot, so the vanilla TM stays untouched.

The letterforms come from the TTF conversions committed in the sibling
speedfog-racing checkout (server/speedfog_racing/static/fonts/, generated by
its tools/generate_brand_assets.py), so both projects draw the wordmark from
the same faces.

The output is committed; re-run this script only to change the design, then
regenerate the overlay (see docs/title-screen.md). Standalone from the project
venv: requires Pillow and the sibling checkout. Deterministic, but glyph
rasterization varies across Pillow/FreeType versions, so a different
environment may produce a byte-different (visually identical) file.
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

W, H = 2532, 1532

RACING_FONTS = (
    Path(__file__).resolve().parent.parent.parent
    / "speedfog-racing"
    / "server"
    / "speedfog_racing"
    / "static"
    / "fonts"
)
COND700 = RACING_FONTS / "barlow-condensed-700-latin.ttf"
COND600 = RACING_FONTS / "barlow-condensed-600-latin.ttf"

BRASS = (200, 164, 78, 255)  # #c8a44e
OFFWHITE = (232, 230, 225, 255)  # #e8e6e1

# validated composition (2026-08-08): wordmark centered above the ELDEN RING
# lettering, between the top arc and the logo
SIZE = 128
CENTER_X = 1266
BASELINE = 400


def draw_tracked(
    draw: ImageDraw.ImageDraw,
    x: float,
    baseline: int,
    text: str,
    font: ImageFont.FreeTypeFont,
    fill: tuple[int, int, int, int],
    tracking: float,
) -> float:
    """Draw text char by char with letter-spacing; return the end x."""
    for ch in text:
        draw.text((x, baseline), ch, font=font, anchor="ls", fill=fill)
        x += font.getlength(ch) + tracking
    return x


def tracked_width(text: str, font: ImageFont.FreeTypeFont, tracking: float) -> float:
    """Advance width of tracked text, excluding the trailing tracking."""
    w = sum(font.getlength(ch) for ch in text) + tracking * len(text)
    return w - tracking if text else 0.0


def route_underline(
    width: int, color: tuple[int, int, int, int], ss: int = 4
) -> Image.Image:
    """The hero route underline: triangle, line, ring, line, terminal square.

    Drawn supersampled at ss then downscaled (Pillow shapes are aliased at
    1x). Logical height 24px, the line rides the vertical center.
    """
    LH = 24
    img = Image.new("RGBA", (width * ss, LH * ss), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    cy = LH // 2 * ss
    lw = 4 * ss
    tri_w, tri_h = 16 * ss, 20 * ss
    ring_r, ring_sw = 9 * ss, 4 * ss
    sq = 18 * ss
    end = width * ss
    mid = end // 2
    d.polygon([(0, cy - tri_h // 2), (0, cy + tri_h // 2), (tri_w, cy)], fill=color)
    d.rectangle([tri_w, cy - lw // 2, mid - ring_r - 3 * ss, cy + lw // 2], fill=color)
    d.rectangle(
        [mid + ring_r + 3 * ss, cy - lw // 2, end - sq, cy + lw // 2], fill=color
    )
    d.ellipse(
        [mid - ring_r, cy - ring_r, mid + ring_r, cy + ring_r],
        outline=color,
        width=ring_sw,
    )
    d.rectangle([end - sq, cy - sq // 2, end, cy + sq // 2], fill=color)
    return img.resize((width, LH), Image.LANCZOS)


def main() -> int:
    for f in (COND700, COND600):
        if not f.exists():
            print(
                f"Error: {f} not found (requires the sibling speedfog-racing "
                "checkout; its tools/generate_brand_assets.py generates the TTFs)",
                file=sys.stderr,
            )
            return 1

    overlay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(overlay)

    f700 = ImageFont.truetype(str(COND700), SIZE)
    f600 = ImageFont.truetype(str(COND600), SIZE)
    tracking = 0.04 * SIZE
    gap = f700.getlength(" ") + 2 * tracking
    w1 = tracked_width("SPEEDFOG", f700, tracking)
    w2 = tracked_width("RACING", f600, tracking)
    total = w1 + gap + w2
    x0 = CENTER_X - total / 2
    draw_tracked(d, x0, BASELINE, "SPEEDFOG", f700, OFFWHITE, tracking)
    draw_tracked(d, x0 + w1 + gap, BASELINE, "RACING", f600, BRASS, tracking)
    overlay.alpha_composite(
        route_underline(int(total), BRASS), (int(x0), BASELINE + 18)
    )

    out = Path(__file__).resolve().parent.parent / "data" / "title_screen_overlay.png"
    overlay.save(out, optimize=True)
    print(f"saved {overlay.size} -> {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
